apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxmox-cjsolsen-com
  namespace: external-dns
spec:
  secretName: proxmox-cjsolsen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "proxmox.local.cjsolsen.com"
  dnsNames:
  - "proxmox.local.cjsolsen.com"