apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: udr-cjsolsen-com
  namespace: external-dns
spec:
  secretName: udr-cjsolsen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "udr.local.cjsolsen.com"
  dnsNames:
  - "udr.local.cjsolsen.com"