apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:2zc15Kq2b5eU/JjCWWRnfbe4zqOCIEPe2tcw5DKpShq+Yz0/S8WQCFoYxofQVdkxnACbyaYpkis=,iv:Plz+lcyXlc0zf84lcKcxLks0T69BXDQoz/88tjCBww4=,tag:RulhhGBBczya0owrL/qHeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rz5awd2ratsapyp3e90ajqpne0vp93clmfgg34ahv3aruzdlm4hsmd6qsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdmllM3ZVM2hjOXdOdUV0
            ajN4WmNPZkVkeXVTMEM5ejRIRndlTmptY1RZCjcrNEIyRWgyV21zMlNGbDVXamN5
            a3RUSEpLOTJVZjluMWtpdjRqWHlpdGcKLS0tIDNyNkpmOThjMDlYWlRMYm80aUNN
            elNoZHFTUXFkbCtnbjM1K3pPbHlyRFUKEq5t4IfgK39VP2QyNYkSj3MENgW2fX19
            T/B200p4kLdz2oCKYIRT8LJ8/SIKSUcEyHQV0r9QTn6qTq1bLflVXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T13:49:50Z"
    mac: ENC[AES256_GCM,data:R2HbsulambdDulLiR+abTaoks7VZWYrx9zPWrabSUapcKkSuEsK5LlN3P8IAH1dJOgvTkj/oRrau/3UmWbsGx3/F2O1sZKaWhQm9wCWAkkpWGIJa6Ut8OvSaKyDUJZOtXBt5h+cS0r8i7//LhXrCPmnyT8jCvu03KhD/XAC02G0=,iv:6ko/IU9U17yEQoEbjvAms/Yyway6SUlYECmiXF2PXeI=,tag:ZvOdg0dHzK4TlrRmqAuHBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
