---
# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
# Area
- name: area/ansible
  color: "72ccf3"
  description: "Changes made in the ansible directory"
- name: area/github
  color: "72ccf3"
  description: "Changes made in the github directory"
- name: area/kubernetes
  color: "72ccf3"
  description: "Changes made in the cluster directory"
# Others
- name: bug
  color: "d73a4a"
  description: "Something isn't working"