---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cjsolsen-com
  namespace: nextcloud
spec:
  secretName: nextcloud-cjsolsen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "nextcloud.cjsolsen.com"
  dnsNames:
  - "nextcloud.cjsolsen.com"
