apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
data:
  nextcloud-username: c2VydmVyYWRtaW4=
  nextcloud-password: Qmh5ZW1nOUZvOGFxVHJDUEJKeWN4cmdUQnhRYzJL