apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-configmap
  namespace: cloudflare-ddns
data:
  TZ: "Europe/Zurich"
  DOMAINS: cjsolsen.com
  PROXIED: "true"
  IP6_PROVIDER: "none"
  DELETE_ON_STOP: "false"
  UPDATE_CRON: "@every 10m"
  UPTIMEKUMA: "https://uptime-kuma.local.cjsolsen.com/api/push/dau38c80rV?status=up&msg=OK&ping="
