apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - image: oznu/cloudflare-ddns:latest
        name: cloudflare-ddns
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cloudflare-ddns-configmap
          - secretRef:
              name: cloudflare-ddns-secret
