apiVersion: v1
kind: Secret
metadata:
    name: website-ghcr-secret
    namespace: website
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Nd0Pu9Krf8T7v3Qrv9bulIjQ76bdaCKXsm9fyv/l2OePMB/z58B8rHABEjul92SKBC0SG9Vi2t1oiZEA5+nUFyoCWR0FIBzUI9n1aFuOa9udM71Rn8GrLPHr91ixINOVMDN4gWb+BneBsBIHJlW0gHvBqNdkktEd+ZlnQyDcrCCH9PWwWgChJQ==,iv:C+e3GCU1yYhRH9vZomBV+DeETHmYwNBMTqXb1m4uE4c=,tag:T3TArUqa3B5U0sr+bFZ5iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rz5awd2ratsapyp3e90ajqpne0vp93clmfgg34ahv3aruzdlm4hsmd6qsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcmJpU3UyVU8wc1lMUERi
            TnREbWJ4Q2FJNHVyUytGeERsMnoyNkJXOUVVCnRSSVZweTF1YnB6YzV6QzRBZEgx
            blpLT3Jlb2NrejFwak5UOWZBU1lSeG8KLS0tIGJVdGlJVnYxczV6cytyeUhRdUJx
            ZHdxYVlwQTF2VmEyOUk0Yy9mVlRsZFUKEi4D7bUW3MknyZYIXDwZcmQL2sfBkpsW
            w9ZcEgEVWHApp5CrCHupNXQIvkbxEHOAvHnxBLrzceBxRrwvuMGT3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T11:08:26Z"
    mac: ENC[AES256_GCM,data:mJS6fY8pS/KTTkJ8C/dhWbhCfafM/aes1mbOj4mf1XBXQe7ihHhXMjCm83aqRBZjqdqC/G1lPEaTglxCRoyFPwuVBRx55Q/0HzypOct60f9ld1/ZZKXN8PCIKrFtjKP5ilSIBKdr5ZXVaCzE7LIS9i3y10xz+OWOWAmiHCyU0U8=,iv:ZkwC20M9MWtutNLxKkGa6Oq3l1Lg+mgO0NMK43i/fcA=,tag:sCdIyklrDr2nlpU83kWKmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
