apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: pihole
type: Opaque
data:
    WEBPASSWORD: ENC[AES256_GCM,data:xPnjQXJHxVR24TVPMVKfLvL/M/AJKXDeVWnq7R9huM4DYYf5JGeRxw==,iv:3fjZutHnMjLcnXFhw0cWZY4Z3HkR76FMgcYohy4s8x8=,tag:IZuTpC6hNUpuitrKzj2TYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rz5awd2ratsapyp3e90ajqpne0vp93clmfgg34ahv3aruzdlm4hsmd6qsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNEwvQmVHejBlQ0pOR1hR
            VklweXVPOEtldHdUQ0VHTFpSS281N3IvUEY0CmRraERPMmwyMzBuWDBLNHV1TzdW
            RjJNbVBKUjFUMjZpMXVDMTZMVVdrVDgKLS0tIEtaVXFuK2RsTkYwNWdsZFBES0Np
            WE01WlhBTFl3di93MVY1aXp1WWdLSlkKVUenQxSuq7bw+7KZw8FRL0G6DnaGNBvv
            vqqQkaKnb1cUegvp+tP+3vrg8AbgkTBnhRFt7XXaUcTgQP+RIfFJHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T13:55:50Z"
    mac: ENC[AES256_GCM,data:TllbkMRWw2h6Fcpvcxxhk26aDHY4GJS38Z+tlbd244u1MIapB6stCj9TqYFLMJwo82g0d1URkJwvili0rAt0tAxd6yHvh0nKpjL083k7MQn/BQEhOEbDFVZitvGZ+JxrwWT0xki5TCnfCTGNiUS8Xvz0e/Gt5pSp9hhZ3tE5Yr8=,iv:nBjbuClgxVUOuP38BABYGaUR+gP+wK29FeMJANoU4eY=,tag:XApz/TstaJPOQWMiSxnF0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
