apiVersion: v1
kind: Secret
metadata:
    name: l1nkrsite-ghcr-secret
    namespace: l1nkrsite
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:YLc4PLXmqqa7SqVgN4khGoYCfRvZlt1u9NzHGdu9WpC378GfSRxmVsn8Ayxj7El/OwCDUWAj8X3JDLN7YMG1neqs5YZbSp/0C64VhAy//muyW8BILPcZMx8ZR7EmBy1GGbjSx7B7KlDqn9BCWZWyqVXy0dLFgt9xLOUGiaQIp1VIaINL6CSkrQ==,iv:j77GXb4z9XVd4i8+ce/VYE8FGNko7q8wuZkWsUwE9L0=,tag:UFbEvlX7P/cmvpTDdCupBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rz5awd2ratsapyp3e90ajqpne0vp93clmfgg34ahv3aruzdlm4hsmd6qsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUlNpZFpYUzE2TEJJcnZT
            QlU5K3ZBQ1YvcjlRZUU2empEUTlhOE82TFdzCjVJTGhkZGhXalhRclk5SUdQQUp0
            RE5SSmZzR1JPN3pCQjA5cUxTakZWZUEKLS0tIDdjUUZpeFJoaTVtcWxpOEhuUFor
            bHlPSDUySzAyZndzQnRWZnRhWXJFL1EKGg8t3EJuEuC2k0a6kJNhFIZhqn1fWNNG
            TpndpNJMsVxC+q7y0NRa4Ylpulc5LrvRH/QsWFSxKpXOkodcSbKQgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T13:53:19Z"
    mac: ENC[AES256_GCM,data:WvZ1YSTbiSpIhxpWIMApmZ4qJCgGjKoyjdwZ0loaQy3JLXbKKsVyYhxANxFCjpunaMXYJlalKdyuMe4/mMnp7x/p91aM9/xX8pO2v9e075aXzezQ905ABywMLOh88U0+SQb09LChQa0curz28D8pOqwyVJ2iOljfazogl8OSd+g=,iv:CFbzIZxr8Xg5yjIBVSXxJF3O5Oot9Jk3t3gVqmVhFh0=,tag:WQlAGMmQM5Ug+NoKhYvMyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
