apiVersion: v1
kind: Secret
metadata:
    name: l1nkrsite-ghcr-secret
    namespace: l1nkrsite
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:BjIMuv78hoH8S0KYeAoOnRFopB/6JunkpyFQEcLCBdze9beqihyKE7oioO5pOhIVtkAn/ybzzlvVi2MMD3C/W7E9RIroW2dRZTef7CdVIBnGQ0wZ5LCfh6SNUHcs4+1tpLEWjAGmlvoTOE8ClKsFQK0rvsjat0xDZkXPIYdwly+XuqFT/E18tQ==,iv:edQAvDsHUO5pPdOQTRSrZOCRycP+mbRvr4q1AC+XHe8=,tag:7i2LRIAjS0YQBcJaS7R7pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rz5awd2ratsapyp3e90ajqpne0vp93clmfgg34ahv3aruzdlm4hsmd6qsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRmlrS2hTY28vSDRXNm1I
            c2pqV1RTS01ERG16ZWd6dVdCRHA4MldONlJrCjVEY0phYWdiSlNUdDVnVUIrTW9v
            V0NqOHBMeS81MktNRWlVRE1EMkU0Y2sKLS0tIEpSNHA0NWhhNTNRT3RYNytTTGJh
            VkFQOC9JYkRGZHBqK3ZaTnRBaUJ4OVkK0xU40bOWFmEw7IetXCsX8EAP6b7wkbs/
            ORSVkdN6CIK+GSqrDpzUW6PkPjhhYsbUuxYgqsNe5ojyEw4lH1e1LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-05T18:09:08Z"
    mac: ENC[AES256_GCM,data:jNTT45ILXsTmU72lhbiVw5zzgCGDNQn+E9SNT8lBBZqebzNcUH9PFQksbf8D4+7v5yRZZvfouM49C1tRpQOBWsKtdDZe9PP5MdmpeXcsrhZ6F46r7OZvL1GmDbyHLZuTLm876ha2BAWcsyEOgf4+9I+ZDy9BUbUUW5Qr2SX4CjE=,iv:gyl0hyGWeOedfxRLluQBEWDlgbtulbtqrbrpgDYk/R4=,tag:MG71QlPkZfor99YGsp8aHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
