apiVersion: v1
kind: Secret
metadata:
    name: l1nkrsite-ghcr-secret
    namespace: l1nkrsite
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:s9/qsjFsPd98cv0/71Vj+VewbNEpP03D+0ok8PByyC1xmN6Q78yVRa49kqAH9WQTM+SAgOtnHZIZgqkJAIKtUi1V2WuCPOnZoQ1MVsD4elQynLYIg9mnL67eV6JqR7qPpur5Saefl2vKiRIn+bptNcHz3OreyNL69VBY+kxM2Cd9wreLGn4fkw==,iv:5GI6picnh/Mnf4QxQkRC5hoU+quUy6TChBJ1tLCrprY=,tag:UgARxV/pFTYcGSs7PYU8Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rz5awd2ratsapyp3e90ajqpne0vp93clmfgg34ahv3aruzdlm4hsmd6qsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycFErL3owKy9jMjMwQmlE
            WFFtT0NvWjVNYzROT0VEeGJmeU5IOGZ4VFNVCnNwRDhLTzkySFpRR2ZhNllCek54
            anp1QUVuRXpGU3JLNzZhWjhFLzNMcFkKLS0tIDNsK2VKbktxcERGV1p4ODd4K1I0
            TW4xNU1EQVFNV3JoLzBsTVZYT0R6OFEKPPG/zm0gL/fG/nE7iTaHnZ4qbn63/J4G
            ZcJVgrUsvVFOZHezin9LEfrpbe0T+glvw67OtUKx74h0GemyRH9b/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T17:39:05Z"
    mac: ENC[AES256_GCM,data:B3isjjZ244mnSIFEHyLGJbBALnGD6aZyM0Gi4yd7blNKRZuBkz3Ndh3q1NJRoK8ARLqcZ3btDQpCNdABAnE5vjUZg+tBL0JiL00FlfHJ5RThqqjpBW87rNodxYDm0ipWXrBwVfuFqCbVRPoNe4z8WVgfsdPSxzgnUhn4O3+Dfkw=,iv:ZPhhhoEALY9dL+/hlX+jH2IETrkU1ifpM0Dt7txXwc4=,tag:DQTcTvoKrtkVqRPBeGfthA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
