apiVersion: v1
kind: Secret
metadata:
    name: l1nkrsite-ghcr-secret
    namespace: l1nkrsite
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7g1bdV/zSLLGy/AeF9mE0iisHwn/VdCGi7xdM4LQvLGzMuy9E6ZU2o0HPgSCLXLS2T2XIzSGbuwjO6IwGM6o+icUA2QxyWpaJj5Hyp06/dw8mP4UarWSOEe+dpjRnWHp/9iSdw/2YsdmVp1wrKvoLscIP5turuMeL5OpkmjkdYWj3SAg+0XkZQ==,iv:4wnbAk+naQ/RKaeF6+mts/S/iy5eCA+zYdLJu+8BrwM=,tag:7UTIPmuUbM6/djeIQIJ1mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rz5awd2ratsapyp3e90ajqpne0vp93clmfgg34ahv3aruzdlm4hsmd6qsu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYlkyWk1yenFWWmhUVjMz
            RGhtMGMwdEJiNjRjcjY0Vk1xbzIzdFdIQjNrCnJ3OE4yVDRiVXQ5Um5obXFOQmtR
            NUFnZDRLdzFlN1JRRnZtaGMxSU1kZVEKLS0tICtZQTFMV2RrNFlrQ3M2RWM1cWYv
            eWJSYWMwakNVTVJPR0hka3BHMlRZdHcKxZvpdJRASM/NeQJAmwC7DU2Awke6vgwh
            LNM7e+lga3j6knM2v1Y2fwOi+C9if3zw8iNTGQXOIlfAy22cqe7RSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T15:32:03Z"
    mac: ENC[AES256_GCM,data:eK7O/fY2nyMxhneLUlpU/TcxfR7cOKCVe3cNj5jpBoNyxq/rzNXROOEZIAw5M30kYhJD/YUo5GsyrdZyKqYCu93AggSPIThIn10LoB/dP8rN18i3TRaqGWwlnh+NiFmhDc/eaRWNf3Svu1IijkIfmGPxQ/MKPUxSb6PRwJQ+BUA=,iv:aJte1pb9Nc7M1K8t/Ly/Y9N4KWfhfd+nm3Orx8OAe0s=,tag:UthnrMMtqdRjzGXcKtmj1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
