---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: l1nkr-cjsolsen-com
  namespace: l1nkrsite
spec:
  secretName: l1nkr-cjsolsen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "l1nkr.cjsolsen.com"
  dnsNames:
  - "l1nkr.cjsolsen.com"