apiVersion: apps/v1
kind: Deployment
metadata:
  name: little-link
  namespace: little-link
  labels:
    app: little-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: little-link
  template:
    metadata:
      labels:
        app: little-link
    spec:
      containers:
      - image: ghcr.io/techno-tim/littlelink-server@sha256:69930c8c527c6b5e06ff3ac79a091d5b47ca568e6bd1b02823c0c0c5954c5e97
        name: little-link
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: little-link-configmap
