apiVersion: apps/v1
kind: Deployment
metadata:
  name: little-link
  namespace: little-link
  labels:
    app: little-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: little-link
  template:
    metadata:
      labels:
        app: little-link
    spec:
      containers:
      - image: ghcr.io/techno-tim/littlelink-server@sha256:19852db8e320cc3ef17f22d6f5b573ccaf03b05cd5f6542d809ff37636a38e5a
        name: little-link
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: little-link-configmap
