apiVersion: apps/v1
kind: Deployment
metadata:
  name: little-link
  namespace: little-link
  labels:
    app: little-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: little-link
  template:
    metadata:
      labels:
        app: little-link
    spec:
      containers:
      - image: ghcr.io/techno-tim/littlelink-server@sha256:6641f1d9a75e7a90e1c329ba66503a55dac7b53c5c4463cf21a8df9db3903521
        name: little-link
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: little-link-configmap
