---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: littlelink-cjsolsen-com
  namespace: little-link
spec:
  secretName: littlelink-cjsolsen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "littlelink.cjsolsen.com"
  dnsNames:
  - "littlelink.cjsolsen.com"