- name: Setup stuff on a new linux VM
  hosts: 'servers'
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true