apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Cjso Homepage

    background:
      image: https://
      blur: sm
      saturate: 100
      brightness: 50
      opacity: 100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 3
      DNS:
        header: true
        style: row
        columns: 3
      Network:
        header: true
        style: row
        columns: 3
      Other:
        header: true
        style: row
        columns: 3
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: ""
  widgets.yaml: ""
  docker.yaml: ""