apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Cjso Homepage

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Other:
        header: true
        style: row
        columns: 3
  services.yaml: |
    - Other:
        - GitHub:
            icon: github.svg
            href: https://github.com/chrede88
            description: my github repo
        - Website:
            icon: https://raw.githubusercontent.com/chrede88/k3s-cluster/main/cluster/home/homepage/icons/cjso.svg
            href: https://cjsolsen.com
            description: main website
        - LinkTree:
            icon: https://raw.githubusercontent.com/chrede88/k3s-cluster/main/cluster/home/homepage/icons/cjso.svg
            href: https://l1nkr.cjsolsen.com
            description: linktree website
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - search:
        provider: duckduckgo
        target: _blank

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  bookmarks.yaml: ""
  docker.yaml: ""
  custom.css: ""
  custom.js: ""