---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cjsolsen-com
  namespace: homepage
spec:
  secretName: homepage-cjsolsen-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "homepage.local.cjsolsen.com"
  dnsNames:
  - "homepage.local.cjsolsen.com"
