image:
  repository: quay.io/jetstack/cert-manager-controller
  pullPolicy: IfNotPresent
  tag: v1.14.2
installCRDs: false
replicaCount: 2
extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
  - --dns01-recursive-nameservers-only
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 1.1.1.1
    - 1.0.0.1
